### ISSUE TITLE
Trouble Implementing 

### ISSUE THREAD

**Issue by SadBoyENVY** [tedewaard/dwanium#2]
We are trying to implement this and are getting an error for line 1 and line 120 as well. Any insight on how to resolve? Any thing would be greatly appreciated!

"thread 'main' panicked at 'Problem with the Tanium API response. Check that the API token is valid: error decoding response body: missing field `data` at line 1 column 82', src/tanium.rs:120:23"

**Comment by tedewaard** [comment]
When you created the Tanium API key you had to add your public IP address. I would first double check that the public IP from where you're running it is correct. I've run into that a few times from just hoping networks within the office because I'm routing out through a different IP.

**Comment by SadBoyENVY** [comment]
The public IP was in fact the issue. Thank you for the quick response!
